services:
  # Development overrides
  gateway:
    volumes:
      - ./gateway:/app  # Mount source code for hot reload
    environment:
      - DEBUG=True
      - ENVIRONMENT=development
      - FRONTEND_URL=http://localhost:3000
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  front:
    volumes:
      - ./front:/app  # Mount source code
      - /app/node_modules  # Exclude node_modules
      - /app/.next  # Exclude build directory
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-https://icgwlycqhxjsmjsiodlj.supabase.co}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZ3dseWNxaHhqc21qc2lvZGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzkwNTEsImV4cCI6MjA2OTE1NTA1MX0.fEX1OOCqM2-tMQ4gZvOySD3mYaTA_XLc2sO_OSuZp1U}
    command: bun run dev

  postgres:
    ports:
      - "5432:5432"  # Expose postgres for local development

  redis:
    ports:
      - "6379:6379"  # Expose redis for local development